---
name: medium_tags
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0
  html_unescape: ^2.0.0
  equatable: ^2.0.3
  provider: ^6.0.2
  flutter_inappwebview: ^5.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
